import React from "react";

const Chords = () => (
  <div>
    <h1 className="text-4xl font-bold">Chords</h1>
    <p>
      Four-note chords, played by virtual analogue or wavetable oscillators. The
      virtual analogue oscillators emulate the stack of harmonically-related
      square or sawtooth waveforms generated by vintage string & organ machines.
    </p>

    <p>
      <b>HARMONICS</b>: chord type.
    </p>

    <p>
      <b>TIMBRE</b>: chord inversion and transposition.
    </p>

    <p>
      <b>MORPH</b>: waveform. The first half of the knob goes through a
      selection of string-machine like raw waveforms (different combinations of
      the organ and string “drawbars”), the second half of the knob scans a
      small wavetable containing 16 waveforms.
    </p>

    <p>
      <b>AUX</b>: root note of the chord.
    </p>
    <img
      src="https://mutable-instruments.net/modules/plaits/images/model_07_knobs.png"
      alt=""
    />
  </div>
);

export default Chords;
